//go:build ignore

// Command repack_node_runtime refreshes PiG's embedded Node runtime archive after patches change files under
// runtime-node/. The module zip omits vendor/ directories, so the runtime cannot be regenerated from source;
// instead, every archive entry keeps its content except the files that differ on disk.
//
// Run it from coding/extension/host/subprocess inside the module that is being patched:
//
//	GOWORK=off go run /path/to/repack_node_runtime.go
package main

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"io"
	"os"
	"regexp"
	"strconv"
	"strings"

	"github.com/klauspost/compress/zstd"
)

const (
	archivePath  = "runtime-node.zip"
	metadataPath = "runtime_node_digest_generated.go"
	sourceRoot   = "runtime-node"
)

type entry struct {
	name string
	data []byte
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "repack_node_runtime:", err)
		os.Exit(1)
	}
}

func run() error {
	entries, err := readArchive()
	if err != nil {
		return err
	}
	recorded, err := recordedDigest()
	if err != nil {
		return err
	}
	if got := digest(entries); got != recorded {
		return fmt.Errorf("archive digest does not match %s; the entry order or content is not what this tool expects", metadataPath)
	}
	changed := 0
	for i, e := range entries {
		data, err := os.ReadFile(e.name) // entry names already start with runtime-node/
		if err != nil {
			if os.IsNotExist(err) {
				continue // vendor/ and other files that the module zip leaves out
			}
			return fmt.Errorf("read %s: %w", e.name, err)
		}
		if !bytes.Equal(data, e.data) {
			entries[i].data = data
			changed++
			fmt.Fprintf(os.Stderr, "repack_node_runtime: patched %s\n", e.name)
		}
	}
	if changed == 0 {
		return nil
	}
	if err := writeArchive(entries); err != nil {
		return err
	}
	source, err := format.Source(fmt.Appendf(nil, "// Code generated by go generate ./coding/extension/host/subprocess; DO NOT EDIT.\n\npackage subprocess\n\nconst nodeRuntimeHash = %q\n", digest(entries)))
	if err != nil {
		return err
	}
	return replaceFile(metadataPath, source)
}

func readArchive() ([]entry, error) {
	raw, err := os.ReadFile(archivePath)
	if err != nil {
		return nil, err
	}
	reader, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		return nil, err
	}
	reader.RegisterDecompressor(zstd.ZipMethodWinZip, zstd.ZipDecompressor())
	var entries []entry
	for _, f := range reader.File {
		if !strings.HasPrefix(f.Name, sourceRoot+"/") {
			return nil, fmt.Errorf("unexpected archive entry %q", f.Name)
		}
		rc, err := f.Open()
		if err != nil {
			return nil, fmt.Errorf("open %s: %w", f.Name, err)
		}
		data, err := io.ReadAll(rc)
		closeErr := rc.Close()
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", f.Name, err)
		}
		if closeErr != nil {
			return nil, closeErr
		}
		entries = append(entries, entry{name: f.Name, data: data})
	}
	return entries, nil
}

func writeArchive(entries []entry) error {
	var buffer bytes.Buffer
	writer := zip.NewWriter(&buffer)
	writer.RegisterCompressor(zstd.ZipMethodWinZip, zstd.ZipCompressor(zstd.WithEncoderConcurrency(1)))
	for _, e := range entries {
		header := &zip.FileHeader{Name: e.name, Method: zstd.ZipMethodWinZip}
		header.SetMode(0o644)
		out, err := writer.CreateHeader(header)
		if err != nil {
			return err
		}
		if _, err := out.Write(e.data); err != nil {
			return err
		}
	}
	if err := writer.Close(); err != nil {
		return err
	}
	return replaceFile(archivePath, buffer.Bytes())
}

// digest matches the generator: SHA-256 over every entry's name followed by its content, in archive order.
func digest(entries []entry) string {
	h := sha256.New()
	for _, e := range entries {
		h.Write([]byte(e.name))
		h.Write(e.data)
	}
	return string(h.Sum(nil))
}

func recordedDigest() (string, error) {
	source, err := os.ReadFile(metadataPath)
	if err != nil {
		return "", err
	}
	match := regexp.MustCompile(`nodeRuntimeHash = (".*")`).FindSubmatch(source)
	if match == nil {
		return "", fmt.Errorf("%s has no nodeRuntimeHash", metadataPath)
	}
	return strconv.Unquote(string(match[1]))
}

// replaceFile swaps the file atomically; the module cache copy may be read-only, so the staged copy is replaced, not written in place.
func replaceFile(path string, data []byte) error {
	temp, err := os.CreateTemp(".", ".repack-*")
	if err != nil {
		return err
	}
	defer os.Remove(temp.Name())
	if _, err := temp.Write(data); err != nil {
		temp.Close()
		return err
	}
	if err := temp.Chmod(0o644); err != nil {
		temp.Close()
		return err
	}
	if err := temp.Close(); err != nil {
		return err
	}
	return os.Rename(temp.Name(), path)
}
